version: '3'
services:
  fastapi:
    image: nlp
    container_name: nlp
    restart: always
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000

    volumes:
      - ./:/app/

  